### ISSUE TITLE
Games Fails to Compile on Mint 18.1 x64

### ISSUE THREAD

**Issue by EvilSupahFly** [xLAva/JediOutcastLinux#54]
I'm trying to build from scratch, having made a few minor alterations to how Force Powers function and behave, but it fails when I try to `make` it, first because of missing files:

Terminal Output from the first run:

```seann@black-beast:~/src/jk2sp $ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug /home/seann/jk2-src/JediOutcastLinux
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/seann/jk2-src/jk2sp
seann@black-beast:~/src/jk2sp $ make
Scanning dependencies of target New_Outcast
[  0%] Building CXX object CMakeFiles/New_Outcast.dir/code/0_compiled_first/0_SH_Leak.cpp.o
/home/seann/jk2-src/JediOutcastLinux/code/0_compiled_first/0_SH_Leak.cpp:6:21: fatal error: windows.h: No such file or directory
 #include <windows.h>
                     ^
compilation terminated.
CMakeFiles/New_Outcast.dir/build.make:62: recipe for target 'CMakeFiles/New_Outcast.dir/code/0_compiled_first/0_SH_Leak.cpp.o' failed
make[2]: *** [CMakeFiles/New_Outcast.dir/code/0_compiled_first/0_SH_Leak.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/New_Outcast.dir/all' failed
make[1]: *** [CMakeFiles/New_Outcast.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
So, I removed the offending line and tried again, this time with a new fail:

```seann@black-beast:~/src/jk2sp $ make
Scanning dependencies of target New_Outcast
[  0%] Building CXX object CMakeFiles/New_Outcast.dir/code/0_compiled_first/0_SH_Leak.cpp.o
/home/seann/jk2-src/JediOutcastLinux/code/0_compiled_first/0_SH_Leak.cpp:8:35: fatal error: ..\smartheap\smrtheap.h: No such file or directory
 #include "..\smartheap\smrtheap.h"
                                   ^
compilation terminated.
CMakeFiles/New_Outcast.dir/build.make:62: recipe for target 'CMakeFiles/New_Outcast.dir/code/0_compiled_first/0_SH_Leak.cpp.o' failed
make[2]: *** [CMakeFiles/New_Outcast.dir/code/0_compiled_first/0_SH_Leak.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/New_Outcast.dir/all' failed
make[1]: *** [CMakeFiles/New_Outcast.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Upon looking closer, I see that the entire `smartheap` directory is missing, as well as `windows.h` and they don't appear to be present in your source tree either. `CODE-mp/smartheap` exists, however, so I copied that over and after fixing the filenames from ALL CAPS, I deleted the build folder contents and ran it again, and this is what I got:

```seann@black-beast:~/jk2-src/jk2sp $ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ../JediOutcastLinux
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
system name: Linux
Detected platform: Win32=0 MacOS=0 Linux=1
Build Type: Debug
-- Configuring done
-- Generating done
-- Build files have been written to: /home/seann/jk2-src/jk2sp
seann@black-beast:~/jk2-src/jk2sp $ make
Scanning dependencies of target jk2sp
[  1%] Building CXX object CMakeFiles/jk2sp.dir/code/game/genericparser2.cpp.o
[  1%] Building CXX object CMakeFiles/jk2sp.dir/code/game/q_math.cpp.o
[  1%] Building CXX object CMakeFiles/jk2sp.dir/code/game/q_shared.cpp.o
[  2%] Building CXX object CMakeFiles/jk2sp.dir/code/client/cl_cgame.cpp.o
[  2%] Building CXX object CMakeFiles/jk2sp.dir/code/client/cl_cin.cpp.o
[  2%] Building CXX object CMakeFiles/jk2sp.dir/code/client/cl_console.cpp.o
[  3%] Building CXX object CMakeFiles/jk2sp.dir/code/client/cl_input.cpp.o
[  3%] Building CXX object CMakeFiles/jk2sp.dir/code/client/cl_keys.cpp.o
[  3%] Building CXX object CMakeFiles/jk2sp.dir/code/client/cl_main.cpp.o
[  4%] Building CXX object CMakeFiles/jk2sp.dir/code/client/cl_mp3.cpp.o
[  4%] Building CXX object CMakeFiles/jk2sp.dir/code/client/cl_parse.cpp.o
[  5%] Building CXX object CMakeFiles/jk2sp.dir/code/client/cl_scrn.cpp.o
[  5%] Building CXX object CMakeFiles/jk2sp.dir/code/client/cl_ui.cpp.o
[  5%] Building CXX object CMakeFiles/jk2sp.dir/code/client/snd_ambient.cpp.o
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp: In function ‘void AS_GetTimeBetweenWaves(ambientSet_t&)’:
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:252:78: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘char (*)[1024]’ [-Wformat=]
  sscanf( parseBuffer+parsePos, "%s %d %d", &tempBuffer, &startTime, &endTime );
                                                                              ^
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp: In function ‘void AS_GetSubWaves(ambientSet_t&)’:
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:286:65: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘char (*)[1024]’ [-Wformat=]
  sscanf( parseBuffer+parsePos, "%s %s", &tempBuffer, &dirBuffer ); 
                                                                 ^
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:286:65: warning: format ‘%s’ expects argument of type ‘char*’, but argument 4 has type ‘char (*)[512]’ [-Wformat=]
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:295:51: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘char (*)[256]’ [-Wformat=]
   sscanf( parseBuffer+parsePos, "%s", &waveBuffer );
                                                   ^
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp: In function ‘void AS_GetLoopedWave(ambientSet_t&)’:
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:346:66: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘char (*)[1024]’ [-Wformat=]
  sscanf( parseBuffer+parsePos, "%s %s", &tempBuffer, &waveBuffer );
                                                                  ^
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:346:66: warning: format ‘%s’ expects argument of type ‘char*’, but argument 4 has type ‘char (*)[256]’ [-Wformat=]
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp: In function ‘void AS_GetVolumeRange(ambientSet_t&)’:
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:375:68: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘char (*)[1024]’ [-Wformat=]
  sscanf( parseBuffer+parsePos, "%s %d %d", &tempBuffer, &min, &max );
                                                                    ^
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp: In function ‘void AS_GetRadius(ambientSet_t&)’:
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:405:66: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘char (*)[1024]’ [-Wformat=]
  sscanf( parseBuffer+parsePos, "%s %d", &tempBuffer, &set.radius );
                                                                  ^
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp: In function ‘void AS_GetGeneralSet(ambientSet_t&)’:
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:423:72: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘char (*)[1024]’ [-Wformat=]
   int iFieldsScanned = sscanf( parseBuffer+parsePos, "%s", &tempBuffer );
                                                                        ^
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp: In function ‘void AS_GetLocalSet(ambientSet_t&)’:
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:482:72: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘char (*)[1024]’ [-Wformat=]
   int iFieldsScanned = sscanf( parseBuffer+parsePos, "%s", &tempBuffer );
                                                                        ^
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp: In function ‘void AS_GetBModelSet(ambientSet_t&)’:
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:545:72: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘char (*)[1024]’ [-Wformat=]
   int iFieldsScanned = sscanf( parseBuffer+parsePos, "%s", &tempBuffer );
                                                                        ^
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp: In function ‘int AS_ParseSet(int, CSetGroup&)’:
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:614:52: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘char (*)[1024]’ [-Wformat=]
    sscanf( parseBuffer+parsePos, "%s", &tempBuffer );
                                                    ^
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp: In function ‘void AS_ParseHeader()’:
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:655:51: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘char (*)[1024]’ [-Wformat=]
   sscanf( parseBuffer+parsePos, "%s", &tempBuffer );
                                                   ^
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:662:68: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘char (*)[1024]’ [-Wformat=]
    sscanf( parseBuffer+parsePos, "%s %s", &tempBuffer, &typeBuffer );
                                                                    ^
/home/seann/jk2-src/JediOutcastLinux/code/client/snd_ambient.cpp:662:68: warning: format ‘%s’ expects argument of type ‘char*’, but argument 4 has type ‘char (*)[128]’ [-Wformat=]
[  6%] Building CXX object CMakeFiles/jk2sp.dir/code/client/snd_dma.cpp.o
[  6%] Building CXX object CMakeFiles/jk2sp.dir/code/client/snd_mem.cpp.o
[  6%] Building CXX object CMakeFiles/jk2sp.dir/code/client/snd_mix.cpp.o
[  7%] Building CXX object CMakeFiles/jk2sp.dir/code/client/snd_music.cpp.o
[  7%] Building CXX object CMakeFiles/jk2sp.dir/code/client/vmachine.cpp.o
[  7%] Building CXX object CMakeFiles/jk2sp.dir/code/encryption/buffer.cpp.o
[  8%] Building CXX object CMakeFiles/jk2sp.dir/code/encryption/cpp_interface.cpp.o
[  8%] Building CXX object CMakeFiles/jk2sp.dir/code/encryption/sockets.cpp.o
[  8%] Building CXX object CMakeFiles/jk2sp.dir/code/ghoul2/G2_API.cpp.o
In file included from /home/seann/jk2-src/JediOutcastLinux/code/ghoul2/G2_API.cpp:27:0:
/home/seann/jk2-src/JediOutcastLinux/code/ghoul2/../qcommon/miniheap.h: In constructor ‘CMiniHeap::CMiniHeap(int)’:
/home/seann/jk2-src/JediOutcastLinux/code/ghoul2/../qcommon/miniheap.h:25:9: error: ‘nullptr’ was not declared in this scope
  :mHeap(nullptr)
         ^
CMakeFiles/jk2sp.dir/build.make:590: recipe for target 'CMakeFiles/jk2sp.dir/code/ghoul2/G2_API.cpp.o' failed
make[2]: *** [CMakeFiles/jk2sp.dir/code/ghoul2/G2_API.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/jk2sp.dir/all' failed
make[1]: *** [CMakeFiles/jk2sp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
seann@black-beast:~/jk2-src/jk2sp $
```

What am I missing? The Full cmake log is at https://paste.ee/p/6LiI3 if that helps at all.

**Comment by xLAva** [comment]
The file 
JediOutcastLinux/code/0_compiled_first/0_SH_Leak.cpp
is not part of the Linux build. The SmartHeap is also only for Windows builds.

I just added a new BUILD.md file. It is an updated description on how to build from source.
Please go back to the original state of the code (before your changes) and try again to build the game using the new instructions in BUILD.md.

If you still got errors there, just post them here again.

**Comment by EvilSupahFly** [comment]
Well, that certainly fixed my original errors! Thanks! =)

The problem now is that I'm getting these new ones instead. I created a clean build using `git clone` and I haven't made any changes to the fresh checkout so in theory, it should compile, right?

```
seann@black-beast:~/jk2-src/clean-build $ git clone https://github.com/xLAva/JediOutcastLinux.git
Cloning into 'JediOutcastLinux'...
remote: Counting objects: 3256, done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 3256 (delta 123), reused 206 (delta 111), pack-reused 2947
Receiving objects: 100% (3256/3256), 57.08 MiB | 6.90 MiB/s, done.
Resolving deltas: 100% (1337/1337), done.
Checking connectivity... done.
Checking out files: 100% (1867/1867), done.
seann@black-beast:~/jk2-src/clean-build $ mkdir jk2sp
seann@black-beast:~/jk2-src/clean-build $ cd jk2sp
seann@black-beast:~/jk2-src/clean-build/jk2sp $ cmake ../JediOutcastLinux
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
system name: Linux
Detected platform: Win32=0 MacOS=0 Linux=1
Build Type: RELEASE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/seann/jk2-src/clean-build/jk2sp
seann@black-beast:~/jk2-src/clean-build/jk2sp $ make -j4
Scanning dependencies of target jk2sp
Scanning dependencies of target jk2gamex86

< -- sucesses trucated -- >

[ 18%] Building CXX object CMakeFiles/jk2gamex86.dir/code/cgame/cg_headers.cpp.o
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/jk2sp.dir/all' failed
make[1]: *** [CMakeFiles/jk2sp.dir/all] Error 2

< -- sucesses trucated -- >

[ 53%] Building CXX object CMakeFiles/jk2gamex86.dir/code/icarus/Instance.cpp.o
/home/seann/jk2-src/clean-build/JediOutcastLinux/code/icarus/BlockStream.cpp: In member function ‘CBlockMember* CBlock::GetMember(int)’:
/home/seann/jk2-src/clean-build/JediOutcastLinux/code/icarus/BlockStream.cpp:332:10: error: ‘nullptr’ was not declared in this scope
   return nullptr;
          ^
/home/seann/jk2-src/clean-build/JediOutcastLinux/code/icarus/BlockStream.cpp: In member function ‘CBlock* CBlock::Duplicate()’:
/home/seann/jk2-src/clean-build/JediOutcastLinux/code/icarus/BlockStream.cpp:366:10: error: ‘nullptr’ was not declared in this scope
   return nullptr;
          ^
[ 53%] Building CXX object CMakeFiles/jk2gamex86.dir/code/icarus/Sequence.cpp.o
CMakeFiles/jk2gamex86.dir/build.make:2990: recipe for target 'CMakeFiles/jk2gamex86.dir/code/icarus/BlockStream.cpp.o' failed
make[2]: *** [CMakeFiles/jk2gamex86.dir/code/icarus/BlockStream.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/jk2gamex86.dir/all' failed
make[1]: *** [CMakeFiles/jk2gamex86.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
seann@black-beast:~/jk2-src/clean-build/jk2sp $ rm -Rf *
seann@black-beast:~/jk2-src/clean-build/jk2sp $ rm -Rf *.*
seann@black-beast:~/jk2-src/clean-build/jk2sp $ ls -Fla
total 8
drwxrwxr-x 2 seann seann 4096 Aug 14 20:42 ./
drwxrwxr-x 5 seann seann 4096 Aug 14 20:21 ../
seann@black-beast:~/jk2-src/clean-build/jk2sp $ cmake -DCMAKE_BUILD_TYPE=Debug ../JediOutcastLinux
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
system name: Linux
Detected platform: Win32=0 MacOS=0 Linux=1
Build Type: Debug
-- Configuring done
-- Generating done
-- Build files have been written to: /home/seann/jk2-src/clean-build/jk2sp
seann@black-beast:~/jk2-src/clean-build/jk2sp $ make -j4

< -- sucesses trucated -- >

[ 17%] Building CXX object CMakeFiles/jk2gamex86.dir/code/cgame/cg_headers.cpp.o
In file included from /home/seann/jk2-src/clean-build/JediOutcastLinux/code/ghoul2/G2_API.cpp:27:0:
/home/seann/jk2-src/clean-build/JediOutcastLinux/code/ghoul2/../qcommon/miniheap.h: In constructor ‘CMiniHeap::CMiniHeap(int)’:
/home/seann/jk2-src/clean-build/JediOutcastLinux/code/ghoul2/../qcommon/miniheap.h:25:9: error: ‘nullptr’ was not declared in this scope
  :mHeap(nullptr)
         ^
[ 18%] Building CXX object CMakeFiles/jk2sp.dir/code/ghoul2/G2_bolts.cpp.o
CMakeFiles/jk2sp.dir/build.make:590: recipe for target 'CMakeFiles/jk2sp.dir/code/ghoul2/G2_API.cpp.o' failed
make[2]: *** [CMakeFiles/jk2sp.dir/code/ghoul2/G2_API.cpp.o] Error 1

< -- sucesses trucated -- >

[ 53%] Building CXX object CMakeFiles/jk2gamex86.dir/code/icarus/Sequence.cpp.o
/home/seann/jk2-src/clean-build/JediOutcastLinux/code/icarus/BlockStream.cpp: In member function ‘CBlockMember* CBlock::GetMember(int)’:
/home/seann/jk2-src/clean-build/JediOutcastLinux/code/icarus/BlockStream.cpp:332:10: error: ‘nullptr’ was not declared in this scope
   return nullptr;
          ^
/home/seann/jk2-src/clean-build/JediOutcastLinux/code/icarus/BlockStream.cpp: In member function ‘CBlock* CBlock::Duplicate()’:
/home/seann/jk2-src/clean-build/JediOutcastLinux/code/icarus/BlockStream.cpp:366:10: error: ‘nullptr’ was not declared in this scope
   return nullptr;
          ^
CMakeFiles/jk2gamex86.dir/build.make:2990: recipe for target 'CMakeFiles/jk2gamex86.dir/code/icarus/BlockStream.cpp.o' failed
make[2]: *** [CMakeFiles/jk2gamex86.dir/code/icarus/BlockStream.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/jk2gamex86.dir/all' failed
make[1]: *** [CMakeFiles/jk2gamex86.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
seann@black-beast:~/jk2-src/clean-build/jk2sp $
```

**Comment by xLAva** [comment]
I just committed an updated version of the CMakeLists.txt file.
Now it should also work to compile with your version of gcc.

Pull my changes and just run cmake ../JediOutcastLinux in your build directory again.

**Comment by xLAva** [comment]
I haven't heard back, so I guess it works.
If not just reopen this issue.

**Comment by EvilSupahFly** [comment]
Sorry! Between work and family, I haven't had the time. I'll run through it all next time I do have time and see what shakes.

Thanks!
